SELECT first_name as 'First Name', Last_Name as 'Last Name' FROM hr.employees;
Select distinct(department_id) from hr.employees;
select * from hr.employees order by first_name desc;
Select first_name, Last_name, Salary, Salary*.15 'PF' from hr.employees;
SELECT employee_id,first_name,last_name,salary FROM  hr.employees ORDER BY SALARY ;
select sum(salary) from hr.employees;
select max(salary), Min(salary) from hr.employees;
select Avg(salary), count(*) as No_of_Employees from hr.employees;
select count(*) from hr.employees;
Select Count(distinct(job_id)) from hr.employees;
Select upper(first_name) from hr.employees;
select substring(first_name,1,3) from hr.employees;
Select trim(first_name) from hr.employees;
select length(First_name), length(last_name) from hr.employees;
select First_name from hr.employees where First_name regexp '(0-9)';
Select first_name, last_name, Salary from employees where salary not between 10000 and 15000;
select first_name, last_name,Department_id from hr.employees where department_id in (30,100);
Select first_name, last_name, Salary from employees where salary not between 10000 and 15000 and department_id in (30,100);
select first_name, last_name, hire_date from hr.employees where year(hire_date) = 1987;
select first_name from hr.employees where first_name like ('%b%') and First_name like ('%C%');
select last_name, job_id, salary from hr.employees where job_id = 'IT_PROG' or job_id = 'SH_CLERK' and salary not in (4500,10000,15000);
select last_name from employees where last_name like '______';
select last_name from employees where last_name like '__E%';
Select job_id, group_concat(employee_id, ' ') 'employee_id' from employees group by job_id;
update employees set phone_number = replace(Phone_number, '124', '999');
SELECT * FROM hr.employees where length(first_name) >=8;
update employees Set email = concat(email, '@example.com');
Select right(phone_number,4) from hr.employees;
SELECT SUBSTRING_INDEX(REPLACE(REPLACE(REPLACE(street_address,',',' '),')',' '),'(',' '),' ',-1) AS 'Last--word-of-street_address' FROM locations;
Select * from locations where length(street_address) <= (select min(length(street_address)) from locations);
select substr(job_title, 1, instr(Job_title, ' ')) from jobs;
Select length(First_name) from hr.employees where last_name like '%__c%';
select first_name, Length(first_name) from hr.employees where first_name like 'A%' or First_name like 'J%' or first_name like 'M%' order by first_name;
Select First_name, Lpad(salary, 10, $) Salary from employees;
select left(first_name,8), repeat('$', floor(Salary/1000)) 'Salary$', salary from hr.employees;
Select first_name, employee_id, last_name, hire_date from hr.employees where day(hire_date) = 7 or month(hire_date) = 7;

